Sprint-4-BackEnd-POO/Eplayers_AspNetCore/AspNetCore_E-PLayers/Controllers/EquipeController.cs
using System;
using System.IO;
using Eplayers_AspNetCore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Eplayers_AspNetCore.Controllers
{
    // localhost:5001/Equipe
    [Route("Equipes")]
    public class EquipeController : Controller
    {
        Equipe equipeModel = new Equipe();
        
        // [Route("Listar")]
        public IActionResult index()
        {
            ViewBag.Equipes = equipeModel.ReadAll();
            return View();
            
        }

        [Route("Cadastrar")]
        public IActionResult Cadastrar(IFormCollection form)
        {
            Equipe NewEquipe = new Equipe();
            NewEquipe.IdEquipe = Int32.Parse( form["IdEquipe"] );
            NewEquipe.Name = form["Name"];

            if(form.Files.Count > 0)
            {
                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Equipes");

                if(!Directory.Exists(folder)){
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
                NewEquipe.Image = file.FileName;
            }
            else
            {
               NewEquipe.Image = "padrao.png";
            }

            equipeModel.Create(NewEquipe);

            ViewBag.equipe = equipeModel.ReadAll();
            return LocalRedirect ("~/Equipes");
        }

        [Route("Equipe/{id}")]
        public IActionResult Excluir(int id)
        {
            equipeModel.Delete(id);
            ViewBag.Equipes = equipeModel.ReadAll();
            return LocalRedirect("~/Equipes");
        }
        
    }
}

Sprint-4-BackEnd-POO/Eplayers_AspNetCore/AspNetCore_E-PLayers/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Eplayers_AspNetCore.Models;
using Microsoft.AspNetCore.Http;

namespace Eplayers_AspNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.Username = HttpContext.Session.GetString("_UserName");
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Sprint-4-BackEnd-POO/Eplayers_AspNetCore/AspNetCore_E-PLayers/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="banner">
        <a asp-area="Link para cadastro" asp-controller="Equipe" asp-action="index" class="btn gradient">INSCREVA-SE</a>
    </div>

    <div class="sobre">
        <div class="container">
            <div>
                <h1>O QUE É MUNDO EM COMUM ?</h1>
                <p> Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis corporis voluptas odio
                    asperiores officia, quisquam eius optio itaque nobis vel. Amet placeat veniam architecto magni
                    at facere eaque adipisci laborum. Lorem ipsum dolor sit amet consectetur adipisicing elit. At
                    ipsum, veniam ad, illum corrupti nisi fugiat repellat harum aspernatur cupiditate aperiam
                    voluptatibus nulla a excepturi facere id non nemo totam! Lorem ipsum dolor sit amet consectetur
                    adipisicing elit. Cum numquam expedita architecto quia debitis sint consequatur! Deleniti sed
                    itaque illum aut officiis, quasi tempora esse id incidunt consequatur, magni ipsa? Lorem ipsum
                    dolor, sit amet consectetur adipisicing elit. Natus, beatae ullam iure blanditiis dolorum illum
                    excepturi tempore a unde, ipsa facilis aut et tempora nam quaerat nemo saepe, minus eaque. Lorem
                    ipsum dolor sit amet consectetur adipisicing elit. Tempore ab recusandae, consectetur dicta
                    molestias aliquid eligendi laboriosam sint optio dolor, accusantium quasi eius ad, placeat atque
                    harum veniam fuga sequi. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet </p>
            </div>
        </div>
    </div>
    <img src="Images/9a6e4f50b0d94f75ce274348f06a6d56.png" alt="Imagem de um 
campeão do lol" class="champion">

    <section id="horarios">

        <div class="container">
            <div class="ao_vivo">
                <h2>AO VIVO</h2>
                <div class="partida">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
            </div>

            <div class="em_breve">
                <h2>EM BREVE</h2>
                <div class="partida">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="partida">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="partida">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
            </div>
        </div>
    </section>

    <div class="container content">
        <section class="noticias">
            <div class="card">
                <img src="Images/Teams/T1.jpeg" alt="Notícia sobra assunto 1">
                <div>
                    <h4>Título da Noticia</h4>
                    <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quibusdam quidem praesentium
                        velit vel sapiente nemo obcaecati veritatis dolorum odio facere, quisquam mollitia quo eum.
                        Aspernatur quam reiciendis ratione dolorem!</p>
                </div>
            </div>


            <div class="card">
                <img src="Images/Teams/T2.jpg" alt="Notícia sobra assunto 1">
                <div>
                    <h4>Título da Noticia</h4>
                    <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quibusdam quidem praesentium
                        velit vel sapiente nemo obcaecati veritatis dolorum odio facere, quisquam mollitia quo eum.
                        Aspernatur quam reiciendis ratione dolorem!</p>
                </div>
            </div>

            <div class="card">
                <img src="Images/Teams/T3.jpeg" alt="Notícia sobra assunto 1">
                <div>
                    <h4>Título da Noticia</h4>
                    <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quibusdam quidem praesentium
                        velit vel sapiente nemo obcaecati veritatis dolorum odio facere, quisquam mollitia quo eum.
                        Aspernatur quam reiciendis ratione dolorem!</p>
                </div>
            </div>

            <div class="card">
                <img src="Images/Teams/T9.jpeg" alt="Notícia sobra assunto 1">
                <div>
                    <h4>Título da Noticia</h4>
                    <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quibusdam quidem praesentium
                        velit vel sapiente nemo obcaecati veritatis dolorum odio facere, quisquam mollitia quo eum.
                        Aspernatur quam reiciendis ratione dolorem!</p>
                </div>
            </div>

            <div class="card">
                <img src="Images/Teams/T5.jpeg" alt="Notícia sobra assunto 1">
                <div>
                    <h4>Título da Noticia</h4>
                    <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quibusdam quidem praesentium
                        velit vel sapiente nemo obcaecati veritatis dolorum odio facere, quisquam mollitia quo eum.
                        Aspernatur quam reiciendis ratione dolorem!</p>
                </div>
            </div>

            <div class="card">
                <img src="Images/Teams/T7.jpeg" alt="Notícia sobra assunto 1">
                <div>
                    <h4>Título da Noticia</h4>
                    <p> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos quibusdam quidem praesentium
                        velit vel sapiente nemo obcaecati veritatis dolorum odio facere, quisquam mollitia quo eum.
                        Aspernatur quam reiciendis ratione dolorem!</p>
                </div>
            </div>
        </section>
        <section class="recentes" id="resultados">
            <h3>PARTIDAS RECENTES</h3>

            <div class="resultado">
                <div class="team">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="placar">
                    <P>3 x 2</p>
                </div>
            </div>
            <div class="resultado">
                <div class="team">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="placar">
                    <P>3 x 2</p>
                </div>
            </div>
            <div class="resultado">
                <div class="team">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="placar">
                    <P>3 x 2</p>
                </div>
            </div>
            <div class="resultado">
                <div class="team">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="placar">
                    <P>3 x 2</p>
                </div>
            </div>
            <div class="resultado">
                <div class="team">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="placar">
                    <P>3 x 2</p>
                </div>
            </div>
            <div class="resultado">
                <div class="team">
                    <strong>SK</strong>
                    <img src="Images/SK.png" alt="Logo da equipe SK">
                    <I>VS</I>
                    <img src="Images/FLA.png" alt="Logo da equipe do Flamengo">
                    <strong>FLA</strong>
                </div>
                <div class="placar">
                    <P>3 x 2</p>
                </div>
            </div>
            <a href="todos_os_resultados.html" class="btn gradient">mais resultados</a>
        </section>
    </div>