Sprint-4-BackEnd-POO/Lucas Nauberth Instadev Real Project/InstaDev_G1_DT/Controllers/PublicationController.cs
using InstaDev_G1_DT.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace InstaDev_G1_DT.Controllers
{
    [Route("Feed")]
    public class PublicationController : Controller
    {
        Publication pubModels = new Publication();

        public IActionResult Feed()
        {
            User user = new User();
            ViewBag.Publications = pubModels.ReadAllItens();
              
            return View();
        }

        [Route("Publicar")]
        public IActionResult Publicar(IFormCollection form)
        {
          
            Publication newPub = new Publication();
          
            newPub.IdPublication = pubModels.idGPublication();
            newPub.Subtitle = form["Subtitle"];
            newPub.Image = form["Image"];


            // Inicio uploud
            if (form.Files.Count > 0)
            {
                //Se sim,
                //Armazenamos o arquivo na variável file
                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/Posts");

                // Verificamos se a pasta Equipes não existe
                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                //localhost:5001           +        + Equipes + equipe.jpg        
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/", folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    // Salvamos o arquivo no caminho especificado
                    file.CopyTo(stream);
                }
                newPub.Image = file.FileName;
            }


            // Uploud termino
            newPub.Subtitle = form["Subtitle"];
           


            // Chamamos o método Create para salvar
            // a novaEquipe no CSV
            pubModels.Create(newPub);
            
           
            return LocalRedirect("~/Feed");
        }

        [Route("Delete")]
        public IActionResult Delete(int id)
        {
            pubModels.Delete(id);
            ViewBag.Publications = pubModels.ReadAllItens();
            return LocalRedirect("~/Feed");
        }
    }
}

Sprint-4-BackEnd-POO/Lucas Nauberth Instadev Real Project/InstaDev_G1_DT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InstaDev</title>

    @switch (@ViewData["Title"])
    {
        case "Cadastro":
            <link rel="stylesheet" href="~/css/register.css" /> @* Pasta do CSS mudada para a "estilo.css" *@
            break;

        case "Login":
            <link rel="stylesheet" href="~/css/login.css" />
            break;

        case "Feed":
            <link rel="stylesheet" href="~/css/feed.css" />
             <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
            break;

        case "Profile":
            <link rel="stylesheet" href="~/css/profile.css" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
            break;

        case "EditProfile":
            <link rel="stylesheet" href="~/css/editProfile.css" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
            break;


        default:
            break;
    }

</head>

<body>
    @* <header class="menu">
        <section class="nav">
            <div class="logo">
                <a asp-area="Voltar para o Feed" asp-controller="Publication" asp-action="Feed">
                    <img src="/imgEdit/Instadev.svg" alt="Logo do Instadev">
                </a>
            </div>

            <div class="search">
                <button class="submit-lupa" type="submit">
                    <i class="fa fa-search"></i>
                </button>
                <input type="text" placeholder="Pesquisar" class="search-input" />

            </div>

            <div class="menu-btn">
                <i class="fas fa-home"></i>
                <i class="far fa-paper-plane"></i>
                <i class="far fa-compass"></i>
                <i class="far fa-heart"></i>
                <div class="perfil">
                    <a asp-area="Direcionamento para a página de perfil" asp-controller="Profile" asp-action="Profile">
                        <img src="/imgEdit/thank-you 2.svg" alt="Foto de perfil">
                    </a>
                </div>
            </div>
        </section>
    </header> *@


    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>